/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mul_21 (
    input [15:0] a,
    input [15:0] b,
    input [3:0] alufn_signal,
    output reg [15:0] out
  );
  
  
  
  reg [15:0] s;
  
  always @* begin
    s = 16'h0000;
    
    case (alufn_signal)
      4'h2: begin
        s = a * b;
      end
      default: begin
        s = 16'h0000;
      end
    endcase
    out = s;
  end
endmodule
