/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module pos_to_led_13 (
    input [1:0] pos,
    output reg [23:0] led
  );
  
  
  
  always @* begin
    
    case (pos)
      1'h0: begin
        led = 24'h0000ff;
      end
      1'h1: begin
        led = 24'h00ff00;
      end
      2'h2: begin
        led = 24'hff0000;
      end
      2'h3: begin
        led = 24'h000000;
      end
      default: begin
        led = 24'h000000;
      end
    endcase
  end
endmodule
