/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shd_26 (
    input [15:0] a,
    input [15:0] b,
    input [3:0] alufn_signal,
    output reg [15:0] out
  );
  
  
  
  reg [15:0] s;
  
  reg [15:0] s0;
  
  reg [15:0] s1;
  
  always @* begin
    s = 16'h0000;
    s0 = 16'h0000;
    s1 = 16'h0000;
    if (alufn_signal == 4'hd) begin
      s = a >> 4'h4;
      s0 = s << 4'h4;
      s1 = b | s0;
    end
    out = s1;
  end
endmodule
