/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shifter_24 (
    input [15:0] a,
    input [3:0] b,
    input [3:0] alufn_signal,
    output reg [15:0] out
  );
  
  
  
  always @* begin
    
    case (alufn_signal)
      default: begin
        out = a;
      end
      4'ha: begin
        out = a << b;
      end
      4'hb: begin
        out = a >> b;
      end
      4'hc: begin
        out = $signed(a) >>> b;
      end
    endcase
  end
endmodule
